### ISSUE TITLE
跑起来后是空白的页面

### ISSUE THREAD

**Issue by shen-lan** [sunlong/h5#1]
`<div id="content"><!-- react-empty: 1 --></div>`

**Comment by 35io** [comment]
访问的路径应该是/#/builder, 比如http://localhost:8080/#/builder

**Comment by dovegq** [comment]
我也是，加了/#/builder也没用，直接用webpack编译到dist运行界面出来了，但是看起来js没有运行起来。

**Comment by MKitty** [comment]
跑起来什么也没有
